/* Reference generator using the original bundled FreeType 1.3.1 renderer.
 * Build after the legacy library has been built:
 * cc tools/cmake/freetype1-reference.c -Ictp2_code/libs/freetype-1.3.1/lib
 *    ctp2_code/libs/freetype-1.3.1/lib/.libs/libttf.a -lm -o /tmp/ft1-reference
 * Run with a bundled TTF path and point size. Output starts with line metrics,
 * then ASCII code, width, height, bearings, advance and summed opacity.
 * These values are an independent oracle, not generated by the new renderer.
 */
#include "freetype.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv)
{
    TT_Engine engine; TT_Face face; TT_Instance instance;
    TT_CharMap charmap; TT_Glyph glyph; TT_Face_Properties properties;
    TT_Glyph_Metrics metrics;
    unsigned char palette[] = {0, 86, 128, 170, 255};
    assert(argc == 3);
    assert(!TT_Init_FreeType(&engine));
    assert(!TT_Open_Face(engine, argv[1], &face));
    assert(!TT_New_Instance(face, &instance));
    assert(!TT_Set_Instance_Resolutions(instance, 96, 96));
    assert(!TT_Set_Instance_CharSize(instance, atoi(argv[2]) * 64));
    assert(!TT_Set_Raster_Gray_Palette(engine, palette));
    assert(!TT_Get_Face_Properties(face, &properties));
    int found = 0;
    for (int k = 0; k < properties.num_CharMaps; ++k) {
        unsigned short platform, encoding;
        TT_Get_CharMap_ID(face, k, &platform, &encoding);
        if ((platform == 3 && encoding == 1) || (platform == 0 && encoding == 0)) {
            assert(!TT_Get_CharMap(face, k, &charmap)); found = 1; break;
        }
    }
    assert(found);
    assert(!TT_New_Glyph(face, &glyph));
    long ascender = 0, descender = 0;
    for (int c = 0; c < 256; ++c) {
        assert(!TT_Load_Glyph(instance, glyph, TT_Char_Index(charmap, c), TTLOAD_DEFAULT));
        assert(!TT_Get_Glyph_Metrics(glyph, &metrics));
        if (metrics.bearingY > ascender) ascender = metrics.bearingY;
        long d = metrics.bbox.yMax - metrics.bbox.yMin - metrics.bearingY;
        if (d > descender) descender = d;
    }
    int baseline = ascender / 64, height = baseline + descender / 64;
    assert(height < 128);
    printf("%d %d\n", baseline, height);
    for (int c = 32; c < 127; ++c) {
        assert(!TT_Load_Glyph(instance, glyph, TT_Char_Index(charmap, c), TTLOAD_DEFAULT));
        assert(!TT_Get_Glyph_Metrics(glyph, &metrics));
        int width = (int)floor(metrics.bbox.xMax / 64.0 + .5) - (int)floor(metrics.bbox.xMin / 64.0 + .5);
        int rows = metrics.bbox.yMax / 64 - metrics.bbox.yMin / 64;
        int top = baseline - metrics.bbox.yMax / 64;
        unsigned char pixels[128 * 128] = {0};
        TT_Raster_Map map = {height, 128, 128, TT_Flow_Down, pixels, height * 128};
        TT_Outline outline;
        assert(!TT_Get_Glyph_Outline(glyph, &outline));
        TT_Translate_Outline(&outline, -metrics.bbox.xMin, (height - baseline) * 64);
        assert(!TT_Get_Outline_Pixmap(engine, &outline, &map));
        unsigned total = 0;
        for (int y = top; y < top + rows; ++y)
            for (int x = 0; x < width; ++x) { assert(y >= 0 && y < height && x < 128); total += pixels[y * 128 + x]; }
        printf("%d %d %d %d %ld %d %u\n", c, width, rows,
               (int)floor(metrics.bearingX / 64.0 + .5), -metrics.bearingY / 64,
               (int)floor(metrics.advance / 64.0 + .5), total);
    }
    TT_Done_Glyph(glyph); TT_Done_Instance(instance); TT_Close_Face(face); TT_Done_FreeType(engine);
}
