set(CTP2_ANET_UNIX_SOURCES
  src/linux/uudp/uudps.c
  src/dp/dictset.c
  demo/utils/logpkt.c
  src/dp/dp2.c
  src/linux/dp/dpmem.c
  src/linux/dp/dpdll.c
  src/dp/dynatab.c
  src/dp/assoctab.c
  src/dp/dprint.c
  src/dp/q.c
  src/dp/ini.c
  src/dp/dpuser.c
  src/dp/dpio.c
  src/dp/hkeytab.c
  src/dp/dptab.c
  demo/utils/dpcrc32.c
  src/dp/delay.c
  src/dp/enumsrv2.c
  src/linux/dp/enumapp.c
  src/linux/dp/launchap.c
  src/dp/dpexcept.c
  src/aeh/aeh.c
  src/aeh/aehmap.c
  src/aeh/aehlog.c
  src/dp/dpprivy.c
  src/dp/dpscore.c
  src/dp/deltas.c
  src/tca/tserv.c
  src/tca/tserva.c
  src/tca/tca.c
  src/tca/tcapw.c
  src/tca/crypttab.c
  src/score/scorerep.c
  demo/utils/mywcs.c
  src/3rdparty/md5/md5c.c
  src/3rdparty/d3des/d3des.c
  src/dp/dpshutdn.c
  src/dp/launchparams.c
)

set(CTP2_ANET_WINDOWS_SOURCES
  demo/utils/dpcrc32.c
  demo/utils/eclock.c
  demo/utils/logpkt.c
  demo/utils/mywcs.c
  src/3rdparty/d3des/d3des.c
  src/3rdparty/md5/md5c.c
  src/aeh/aeh.c
  src/aeh/aehlog.c
  src/aeh/aehmap.c
  src/aeh/detect.c
  src/aeh/tlstuff.c
  src/dp/assoctab.c
  src/dp/delay.c
  src/dp/deltas.c
  src/dp/dictset.c
  src/dp/dp2.c
  src/dp/dpexcept.c
  src/dp/dpio.c
  src/dp/dpprivy.c
  src/dp/dprint.c
  src/dp/dpscore.c
  src/dp/dpshutdn.c
  src/dp/dptab.c
  src/dp/dpuser.c
  src/dp/dynatab.c
  src/dp/enumsrv2.c
  src/dp/hkeytab.c
  src/dp/ini.c
  src/dp/launchparams.c
  src/dp/q.c
  src/score/scorerep.c
  src/tca/crypttab.c
  src/tca/tca.c
  src/tca/tcapw.c
  src/tca/tserv.c
  src/tca/tserva.c
  src/win/dp/dllmain.c
  src/win/dp/dpdllwin.c
  src/win/dp/enumapp.c
  src/win/dp/launchap.c
)
