# Prefer package-provided imported targets; pkg-config is a Unix fallback.
function(ctp2_sdl_package package target pkg)
  find_package(${package} CONFIG QUIET)
  if(NOT TARGET ${target})
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(${package}_PC REQUIRED IMPORTED_TARGET ${pkg})
    add_library(${target} ALIAS PkgConfig::${package}_PC)
  endif()
endfunction()
ctp2_sdl_package(SDL2 SDL2::SDL2 sdl2)
ctp2_sdl_package(SDL2_image SDL2_image::SDL2_image SDL2_image)
ctp2_sdl_package(SDL2_mixer SDL2_mixer::SDL2_mixer SDL2_mixer)
# FreeType 2 API; tested with current 2.14.3. Permit supported distro versions.
find_package(Freetype 2.10 REQUIRED)
find_package(TIFF REQUIRED)
find_package(ZLIB REQUIRED)
find_package(Threads REQUIRED)
if(CTP2_MOVIES)
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(FFMPEG REQUIRED IMPORTED_TARGET libavcodec libavformat libavutil libswscale libswresample)
endif()
