include("${CMAKE_CURRENT_LIST_DIR}/Anet.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/GameSources.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/GameIncludes.cmake")
list(TRANSFORM CTP2_GAME_SOURCES PREPEND "${PROJECT_SOURCE_DIR}/ctp2_code/")
list(TRANSFORM CTP2_GAME_INCLUDES PREPEND "${PROJECT_SOURCE_DIR}/ctp2_code/")
ctp2_parser(slic gs/slic/slic.y gs/slic/slic.l yy y)
ctp2_parser(sliccmd gs/slic/sliccmd.y gs/slic/sliccmd.l sc sc)
ctp2_parser(ldl ui/ldl/ldl.y ui/ldl/ldl.l ldl ldl)
add_custom_command(OUTPUT "${CTP2_GENERATED_DIR}/newdb/lex.dbl.c"
  COMMAND "${CTP2_FLEX}" -i -Pdbl "-o${CTP2_GENERATED_DIR}/newdb/lex.dbl.c" "${PROJECT_SOURCE_DIR}/ctp2_code/gs/newdb/DBLexer.l"
  DEPENDS "${PROJECT_SOURCE_DIR}/ctp2_code/gs/newdb/DBLexer.l" VERBATIM)
if(WIN32)
  list(REMOVE_ITEM CTP2_GAME_SOURCES "${PROJECT_SOURCE_DIR}/ctp2_code/ctp/cifm.cpp")
endif()
add_executable(ctp2 ${CTP2_GAME_SOURCES} ${CTP2_SCHEMA_OUTPUTS}
  ${slic_SOURCES} ${sliccmd_SOURCES} ${ldl_SOURCES}
  "${CTP2_GENERATED_DIR}/newdb/lex.dbl.c"
  ctp2_code/ui/aui_common/aui_bitmapfont_freetype2.cpp)
add_dependencies(ctp2 ctp2_database)
target_include_directories(ctp2 BEFORE PRIVATE
  "${CTP2_GENERATED_DIR}/newdb" "${CTP2_GENERATED_DIR}/slic"
  "${CTP2_GENERATED_DIR}/sliccmd" "${CTP2_GENERATED_DIR}/ldl"
  "${PROJECT_SOURCE_DIR}/ctp2_code" ${CTP2_GAME_INCLUDES})
if(WIN32)
  enable_language(RC)
  target_sources(ctp2 PRIVATE ctp2_code/ctp/ctp2_rsrc/civ3.rc)
  set_target_properties(ctp2 PROPERTIES WIN32_EXECUTABLE TRUE)
  target_link_libraries(ctp2 PRIVATE $<TARGET_NAME_IF_EXISTS:SDL2::SDL2main> wsock32 winmm imagehlp amstrmid)
else()
  target_sources(ctp2 PRIVATE ctp2_code/os/nowin32/nowin32.cpp)
  target_include_directories(ctp2 BEFORE PRIVATE ctp2_code/os/nowin32)
endif()
target_link_libraries(ctp2 PRIVATE ctp2_options ctp2_anet SDL2::SDL2 SDL2_image::SDL2_image
  SDL2_mixer::SDL2_mixer Freetype::Freetype TIFF::TIFF ZLIB::ZLIB Threads::Threads ${CMAKE_DL_LIBS})
if(CTP2_MOVIES)
  target_link_libraries(ctp2 PRIVATE PkgConfig::FFMPEG)
endif()
set_target_properties(ctp2 PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/runtime/ctp2_program/ctp")
foreach(plugin IN ITEMS crater fault geometric plasma2)
  if(plugin STREQUAL "crater")
    set(sources Crater.cpp)
  elseif(plugin STREQUAL "fault")
    set(sources FaultGen.cpp)
  elseif(plugin STREQUAL "geometric")
    set(sources Geometric.cpp FaultGen.cpp)
  else()
    set(sources PlasmaGen2.cpp)
  endif()
  list(TRANSFORM sources PREPEND "${PROJECT_SOURCE_DIR}/ctp2_code/mapgen/")
  add_library(${plugin} MODULE ${sources})
  target_link_libraries(${plugin} PRIVATE ctp2_options SDL2::SDL2)
  target_include_directories(${plugin} PRIVATE ${CTP2_GAME_INCLUDES} "${PROJECT_SOURCE_DIR}/ctp2_code/libs/anet/h")
  if(NOT WIN32)
    target_include_directories(${plugin} BEFORE PRIVATE ctp2_code/os/nowin32)
    set_target_properties(${plugin} PROPERTIES SUFFIX .so)
  endif()
  if(WIN32)
    target_sources(${plugin} PRIVATE ctp2_code/mapgen/MapGenerator.def)
    target_link_libraries(${plugin} PRIVATE ole32 uuid)
    set_target_properties(${plugin} PROPERTIES DEBUG_POSTFIX d)
  endif()
  if(plugin STREQUAL "geometric")
    target_compile_definitions(${plugin} PRIVATE GEOMETRIC)
  endif()
  set_target_properties(${plugin} PROPERTIES PREFIX "" LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/runtime/ctp2_program/ctp/dll/map"
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/runtime/ctp2_program/ctp/dll/map")
  install(TARGETS ${plugin} LIBRARY DESTINATION ctp2_program/ctp/dll/map RUNTIME DESTINATION ctp2_program/ctp/dll/map)
endforeach()
install(TARGETS ctp2 RUNTIME DESTINATION ctp2_program/ctp)
if(BUILD_TESTING)
  add_executable(display-scaling-test tests/display-scaling.cpp)
  target_link_libraries(display-scaling-test PRIVATE ctp2_options SDL2::SDL2)
  target_compile_options(display-scaling-test PRIVATE $<IF:$<CXX_COMPILER_ID:MSVC>,/UNDEBUG,-UNDEBUG>)
  add_test(NAME display-scaling COMMAND display-scaling-test)
  set_tests_properties(display-scaling PROPERTIES ENVIRONMENT "SDL_VIDEODRIVER=dummy")
endif()
if(BUILD_TESTING)
  add_executable(freetype-bitmap-test tests/freetype-bitmap.cpp)
  target_link_libraries(freetype-bitmap-test PRIVATE ctp2_options Freetype::Freetype)
  target_compile_options(freetype-bitmap-test PRIVATE $<IF:$<CXX_COMPILER_ID:MSVC>,/UNDEBUG,-UNDEBUG>)
  set(font_test_files)
  foreach(font IN ITEMS arial arialbd arialbi ariali times timesbd timesbi timesi)
    list(APPEND font_test_files "${PROJECT_SOURCE_DIR}/ctp2_data/default/uidata/fonts/${font}.ttf")
  endforeach()
  add_test(NAME freetype-bitmap COMMAND freetype-bitmap-test ${font_test_files})
endif()

if(WIN32)
  # The selected dependency provider supplies DLL locations through imported targets.
  add_custom_command(TARGET ctp2 POST_BUILD
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different $<TARGET_RUNTIME_DLLS:ctp2> $<TARGET_FILE_DIR:ctp2>
    COMMAND_EXPAND_LISTS VERBATIM)
endif()
if(BUILD_TESTING)
  add_executable(archive-buffer-test tests/archive-buffer.cpp ctp2_code/robot/aibackdoor/civarchive.cpp)
  target_link_libraries(archive-buffer-test PRIVATE ctp2_options SDL2::SDL2)
  target_include_directories(archive-buffer-test PRIVATE ${CTP2_GAME_INCLUDES} "${PROJECT_SOURCE_DIR}/ctp2_code/libs/anet/h")
  target_compile_options(archive-buffer-test PRIVATE $<IF:$<CXX_COMPILER_ID:MSVC>,/UNDEBUG,-UNDEBUG>)
  if(NOT WIN32)
    target_include_directories(archive-buffer-test BEFORE PRIVATE ctp2_code/os/nowin32)
    target_compile_options(archive-buffer-test PRIVATE -ffunction-sections -fdata-sections)
    if(APPLE)
      target_link_options(archive-buffer-test PRIVATE -Wl,-dead_strip)
    else()
      target_link_options(archive-buffer-test PRIVATE -Wl,--gc-sections)
    endif()
  else()
    target_compile_options(archive-buffer-test PRIVATE /Gy)
    target_link_options(archive-buffer-test PRIVATE /OPT:REF)
  endif()
  add_test(NAME archive-buffer COMMAND archive-buffer-test)
  add_executable(tile-encoding-test tests/tile-encoding.cpp ctp2_code/gfx/tilesys/tileutils.cpp ctp2_code/gfx/gfx_utils/pixelutils.cpp)
  add_dependencies(tile-encoding-test ctp2_database)
  target_include_directories(tile-encoding-test BEFORE PRIVATE "${CTP2_GENERATED_DIR}/newdb")
  target_link_libraries(tile-encoding-test PRIVATE ctp2_options SDL2::SDL2)
  target_include_directories(tile-encoding-test PRIVATE ${CTP2_GAME_INCLUDES} "${PROJECT_SOURCE_DIR}/ctp2_code/libs/anet/h")
  target_compile_options(tile-encoding-test PRIVATE $<IF:$<CXX_COMPILER_ID:MSVC>,/UNDEBUG,-UNDEBUG>)
  if(NOT WIN32)
    target_include_directories(tile-encoding-test BEFORE PRIVATE ctp2_code/os/nowin32)
    target_compile_options(tile-encoding-test PRIVATE -ffunction-sections -fdata-sections)
    if(APPLE)
      target_link_options(tile-encoding-test PRIVATE -Wl,-dead_strip)
    else()
      target_link_options(tile-encoding-test PRIVATE -Wl,--gc-sections)
    endif()
  else()
    target_compile_options(tile-encoding-test PRIVATE /Gy)
    target_link_options(tile-encoding-test PRIVATE /OPT:REF)
  endif()
  add_test(NAME tile-encoding COMMAND tile-encoding-test)
endif()
foreach(file IN ITEMS appstr.txt bootserv.txt civpaths.txt anet.inf nguid.ctp)
  configure_file("${PROJECT_SOURCE_DIR}/ctp2_code/ctp/${file}"
    "${CMAKE_BINARY_DIR}/runtime/ctp2_program/ctp/${file}" COPYONLY)
  install(FILES "${PROJECT_SOURCE_DIR}/ctp2_code/ctp/${file}" DESTINATION ctp2_program/ctp)
endforeach()
if(BUILD_TESTING)
  add_executable(map-plugin-lifecycle-test tests/map-plugin-lifecycle.cpp)
  target_link_libraries(map-plugin-lifecycle-test PRIVATE ctp2_options SDL2::SDL2 ${CMAKE_DL_LIBS})
  add_dependencies(map-plugin-lifecycle-test crater fault geometric plasma2)
  add_test(NAME map-plugin-lifecycle COMMAND map-plugin-lifecycle-test
    $<TARGET_FILE:plasma2> $<TARGET_FILE:fault> $<TARGET_FILE:geometric> $<TARGET_FILE:crater>)
endif()

if(BUILD_TESTING)
  set_tests_properties(map-plugin-lifecycle PROPERTIES TIMEOUT 20)
endif()
