# Existing game headers are mutually dependent; keep this search path game-local.
set(CTP2_GAME_INCLUDES
  os/include
  ctp
  ctp/ctp2_utils
  ctp/ctp2_rsrc
  ctp/debugtools
  ui/interface
  ui/netshell
  robot/utility
  robot/pathing
  robot/aibackdoor
  gfx/spritesys
  gfx/tilesys
  gfx/gfx_utils
  gs/database
  gs/fileio
  gs/gameobj
  gs/utility
  gs/world
  net/io
  net/general
  ui/aui_utils
  ui/aui_sdl
  ui/aui_directx
  ui/aui_ctp2
  ui/aui_common
  mm
  robotcom/backdoor
  gs/slic
  gfx/layers
  mapgen
  sound
  GameWatch/gamewatch
  GameWatch/gwciv
  ctp/fingerprint
  ui/slic_debug
  gs/outcom
  ui/ldl
  gs/events
  gs/newdb
  ai/diplomacy
  ai/mapanalysis
  ai/strategy/scheduler
  ai/strategy/agents
  ai/strategy/goals
  ai/strategy/squads
  ai
  ai/CityManagement
)
